{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sample-service.serviceAccountName" . }}
  labels:
    {{- include "sample-service.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.workloadIdentityClientId }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceAccount.workloadIdentityClientId | quote }}
  {{- end }}
{{- end }}
