image:
  repository: ghcr.io/chethankumblekar/tenantforge-${{ values.name }}
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 250m
    memory: 128Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

networkPolicy:
  enabled: true
  metricsScraperNamespace: observability
  metricsScraperPodSelector:
    app.kubernetes.io/name: otel-collector

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
